spring.application.name=pdcc
spring.datasource.url=postgresql://neondb_owner:npg_F0fLXGIPg5YQ@ep-winter-shape-ar4sw4h4-pooler.c-4.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_F0fLXGIPg5YQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
app.base-url=http://localhost:8080
